#! /usr/bin/python

import sys
import git

def main():
	repo = git.Repo()
	print('AAAAAAAAA: %d', len(sys.argv))
	print('BBBBBBBBB: %s' % str(sys.argv))
	print('CCCCCCCCD')
	sys.exit(1)

if __name__ == "__main__":
	main()